### ISSUE TITLE
'Service' object has no attribute 'process'

### ISSUE THREAD

**Issue by RafaelLee** [timgrossmann/instagram-profilecrawl#30]
Hey guys, its me, again...

I'm trying to run that DigitalOcen Ubuntu... but getting that error when I try to run the script. If someone has any tip, would be helpful.

![image](https://user-images.githubusercontent.com/681629/33689518-ee55bfd0-dac6-11e7-8f2e-bdb70a409a50.png)

In the page it says to run Python3.5etc... is that mandatory?

If that's the problem, I'm sorry... but I wanna try it with 2.7 version.

Thanks guys.

**Comment by timgrossmann** [comment]
@RafaelLee I'll probably update this tool from using selenium to doing 4 simple requests...

I researched the graphql endpoints and it seems super easy to get all the information in a matter of seconds for each given profile...

https://github.com/timgrossmann/InstaPy-Research

**Comment by thirupathi-thangavel** [comment]
You need to place `chromedriver` under `assets` directory (create it if it's not there - under `instagram-profilecrawl`)

**Comment by thirupathi-thangavel** [comment]
It works for python 2.7 as well. I just tried it.

**Comment by thirupathi-thangavel** [comment]
You need to place `chromedriver` under `assets` directory. Create it if it's not there (under `instagram-profilecrawl` directory)

**Comment by t-thirupathi** [comment]
You need to place `chromedriver` under `assets` directory. Create it if it's not there (under `instagram-profilecrawl` directory)

**Comment by t-thirupathi** [comment]
It works fine on `python 2.7` as well. I just tested :)

**Comment by timmoh** [comment]
@RafaelLee did it worked for you? please close issue
@timgrossmann should be closed
